routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CanHoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource("/canho",CanHoController::class);

app/Models/CanHo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CanHo extends Model
{
    use HasFactory;
    protected $fillable = [
        "MaCH",
        "TinhTrang",
        "MaCSH",
        "Gia",
        "Tang",
        "MaHD",
        "TenChu"
    ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CanHoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\CanHo;
class CanHoController extends Controller
{
    public function index() {
        $canho = CanHo::paginate(5);
        return view('index',compact("canho")) -> with("i", (request() -> input("page",1)-1) * 5);
    }
    public function create() {
        return view('create');
    }
    public function store(Request $request) {
        CanHo::create($request-> all());
        return redirect()-> route("canho.index")->with("thongbao","Thêm căn hộ thành công");
    }
    public function edit(CanHo $canho) {
        return view('edit',compact('canho'));
    }
    public function update(Request $request, CanHo $canho) {
        $canho ->update($request->all());
        return redirect()-> route('canho.index')-> with('thongbao', 'Cập nhật thành công! ');
    }

    public function destroy(CanHo $canho) {
        $canho ->delete();
        return redirect()-> route('canho.index')->with("thongbao","Xóa thành công! ");
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/Edit.blade.php
@extends("layout")

@section("content")
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        Sửa căn hộ
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('canho.index') }}" class="btn btn-primary float-end">Thêm căn hộ</a></div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form action="{{route('canho.update', $canho->id)}}" method="POST">
                    @csrf
                    @method("PUT")
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <strong>Mã chủ sở hữu</strong>
                                <input type="text" name="MaCSH" class="form-control" placeholder="Nhập mã chủ sở hữu ">
                            </div>
                            <div class="form-group">
                                <strong>Họ và tên chủ sở hữu</strong>
                                <input type="text" name="TenChu" value="{{$canho->TenChu}}" class="form-control" placeholder="Nhập họ và tên">
                            </div> 
                            <div class="form-group">
                                <strong>Gía</strong>
                                <input type="number" name="Gia" value="{{$canho->Gia }}" class="form-control" placeholder="Nhập Gía căn hộ">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success mt-2">Cập nhật</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/create.blade.php
@extends("layout")

@section("content")
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        Thêm căn hộ
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('canho.index') }}" class="btn btn-primary float-end">Thêm căn hộ</a></div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form action="{{route('canho.store') }}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">

                            <div class="form-group">
                                <strong>Mã căn hộ</strong>
                                <input type="text" name="MaCH" class="form-control" placeholder="Nhập mã căn hộ">
                            </div>
                            
                            <div class="form-group">
                                <strong>Mã Hóa Đơn</strong>
                                <input type="text" name="MaHD" class="form-control" placeholder="Nhập mã hóa đồng ">
                            </div>
                            <div class="form-group">
                                <strong>Mã chủ sở hữu</strong>
                                <input type="text" name="MaCSH" class="form-control" placeholder="Nhập mã chủ sở hữu    ">
                            </div>
                            <div class="form-group">
                                <strong>Họ và tên chủ sở hữu</strong>
                                <input type="text" name="TenChu" class="form-control" placeholder="Nhập họ và tên">
                            </div>
                            <div class="form-group">
                                <strong>Gía</strong>
                                <input type="number" name="Gia" class="form-control" placeholder="Nhập Gía căn hộ">
                            </div>
                            <div class="form-group">
                                <strong>Tang</strong>
                                <input type="number" name="Tang" class="form-control" placeholder="Nhập Tầng căn hộ">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <strong>Tình trạng</strong>
                            <select name="TinhTrang" id="" class="form-select">
                                <option value="selected">Chọn tình trạng</option>
                                <option value="Mới">Mới</option>
                                <option value="Cũ">Cũ</option>
                            </select>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success mt-2">Lưu</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">   
                    <div class="col-md-6">Quản lý căn hộ</div>
                    <div class="col-md-6">
                        <a href="{{route('canho.create') }}" class="btn btn-primary float-end">Thêm căn hộ</a></div>
                </div>
            </div>
            <div class="card-body">
                @if(Session::has('thongbao'))
                    <div class="alert alert-success">
                        {{ Session::get("thongbao") }}
                    </div>
                @endif
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Mã căn hộ</th>
                            <th>Tên chủ sở hữu</th>
                            <th>Tình trạng</th>
                            <th>Gía</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($canho as $ch)
                            <tr>
                                <td>{{ $ch ->MaCH }}</td>
                                <td>{{ $ch ->TenChu }}</td>
                                <td>{{ $ch ->TinhTrang }}</td>
                                <td>{{ $ch ->Gia }}</td>
                                <td>
                                    <form action="{{route('canho.destroy', $ch->id) }}" method="POST">
                                        <a href="{{route('canho.edit', $ch->id) }}" class="btn btn-info">Sửa</a>
                                        @csrf
                                        @method("DELETE")
                                        <button type="submit" class="btn btn-danger">Xóa</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

    </div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Thêm sửa xóa sinh viên</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    @yield("content")
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>